name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures complete repository history for better analysis

      # Running the SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provides access to the repo for PR info
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your SonarCloud token for authentication
